### ISSUE TITLE
为何会出现各种编码问题

### ISSUE THREAD

**Issue by qcyclone** [CherrySD/KonachanPic#2]
爬虫小白
在win10环境下各种编码问题

**Comment by CherrySD** [comment]
不知道这个编码问题具体是指什么的。可能和系统关系不大，python2.7对编码处理的不太好

**Comment by qcyclone** [comment]
你当初写的时候在什么平台，什么环境下？
我要改成这样，才能够正常显示中文
las,nex=raw_input(u"请输入页数范围:".encode('gbk')).split(' ')

**Comment by CherrySD** [comment]
呃……我实在win下写的。这个问题是因为win下的控制台是gbk编码，如果你默认输出的话是utf-8，所以就乱码了……

**Comment by Giumo** [comment]
enconv -L zh_CN -x UTF-8 KonachanPic.py  即可

**Comment by CherrySD** [comment]
linux下 楼上这种方法还是蛮方便的
